# Generated by Django 5.0.4 on 2024-05-06 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_applicants',
            new_name='is_applicant',
        ),
    ]
